const legend = {
    '187': 'Murder (police code)',
    '\#2': 'Andrew McCabe, Former FBI Deputy Director',
    'Adm R': 'Admiral Michael S. Rogers, Director of the NSA',
    'AF1': 'Air Force 1, POTUS plane',
    'AG': 'Attorney General',
    'AM': 'Andrew McCabe, Former FBI Deputy Director',
    'Anon': 'Anonymous',
    'ANTIFA': 'Anti-Fascists, Soros backed domestic terrorists',
    'AS': 'Adam Schiff; Antonin Scalia',
    'AUS': 'Australia',
    'AW': 'Anthony Weiner',
    'BC': 'Bill Clinton',
    'BDT': 'Bangladeshi Taka, ref. Bangladesh',
    'BIS': 'Bank for International Settlements',
    'BO': 'Barack Obama; Board Owner',
    'BOD': 'Board of Directors',
    'BP': 'Border Patrol',
    'C-A': 'Central Intelligence Agency',
    'CC': 'Chelsea Clinton',
    'CF': 'Clinton Foundation',
    'CFR': 'Council on Foreign Relations',
    'CIA': 'Central Intelligence Agency',
    'Clowns In America': 'Negative CIA Agents',
    'CM': 'CodeMonkey, 8ch Administrator',
    'COC': 'Chain of Command',
    'CS': 'Civil Service; Sen. Chuck Schumer',
    'CTR': 'Correct The Record',
    'D-J': 'Department of Justice',
    'D\'s': 'Democrats',
    'DC': 'District of Columbia',
    'DEFCON': 'Definite Confirmation (Time Minutes)',
    'DET': 'Detachment',
    'DJT': 'President Donald John Trump',
    'DNC': 'Democratic National Committee',
    'DOE': 'Department of Energy',
    'DOJ': 'Department of Justice',
    'DWS': 'Debbie Wasserman Schultz',
    'EBS': 'Emergency Broadcast System',
    'EM': 'Elon Musk',
    'EMP': 'Electromagnetic Pulse',
    'EMS': 'Emergency Medical Services',
    'EO': 'Executive;der',
    'ES': 'Eric Schmidt',
    'EU': 'European Union',
    'F-I': 'Federal Bureau of Investigation',
    'F&F': 'Fox & Friends',
    'f2f': 'Face to Face',
    'FB': 'Facebook',
    'FBI': 'Federal Bureau of Investigation',
    'FED': 'Federal Reserve',
    'FF': 'False Flag',
    'FISA': 'Foreign Intelligence Surveillance Act',
    'FOIA': 'Freedom of Information Act',
    'GOOG': 'Google, NASDAQ designation',
    'GS': 'George Soros',
    'H-wood': 'Hollywood',
    'HA': 'Huma Abedin',
    'HEC': 'United States House Committee on Ethics',
    'HI': 'Hawaii',
    'HRC': 'Hillary Rodham Clinton',
    'HS': 'Homeland Security',
    'HUMA': 'Harvard University Muslim Alumni',
    'HW': 'Hollywood',
    'IC': 'Intelligence Community',
    'ID': 'Identification',
    'IRS': 'Internal Revenue Agency ',
    'ISIS': 'Israeli Secret Intelligence Service',
    'JA': 'Julian Assange',
    'JB': 'John Brennan, Former CIA Director',
    'JC': 'James Clapper, Former DNI Director; James Comey, Former FBI Director',
    'JFK': 'John Fitzgereld Kennedy',
    'JK': 'John Kerry; Jared Kushner',
    'JS': 'John Solomon',
    'KKK': 'Klu Klux Klan, founded by Democrats',
    'KSA': 'Kingdom of Saudi Arabia',
    'LL': 'Lorreta Lynch, Former Attorney General',
    'LV': 'Las Vegas',
    'MB': 'Muslim Brotherhood',
    'MI': 'Military Intelligence',
    'MIL': 'Military',
    'ML': 'Marshal Law',
    'MM': 'Media Matters',
    'MS-13': 'Latino Drug Cartel',
    'MS13': 'MS-13',
    'MSM': 'Mainstream Media',
    'MW': 'Maxine Waters',
    'MZ': 'Mark Zuckerberg',
    'NASA': 'National Aeronautics and Space Administration',
    'NG': 'National Guard',
    'NK': 'North Korea, also NORK, NOK, NOKO',
    'NP': 'Non-Profit',
    'NSA': 'National Security Agency',
    'NWO': 'New World;der',
    'OCMC': 'Overhead Collection Management Center',
    'OO': 'Oval Office',
    'OP': 'Original Poster; Operation',
    'PEOC': 'Presidential Emergency Operations Center',
    'PG': 'PizzaGate; PedoGate',
    'PM': 'Prime Minister',
    'POTUS': 'President of the United States',
    'PS': 'Peter Strzok',
    'PVG': 'Shanghai Pudong International Airport',
    'R\'s': 'Republicans',
    'RNC': 'Republican National Committee',
    'RR': 'Rod Rosenstein, Deputy Attorney General',
    'SA': 'Saudi Arabia',
    'SAP': 'Special Access Programs',
    'SC': 'Supreme Court',
    'SD': 'State Department',
    'SEC': 'Security; Secure',
    'SH': 'Steve Huffmann',
    'SIGINT': 'Signals Intelligence',
    'SIS': 'Signals Intelligence Service',
    'SK': 'South Korea',
    'SR': 'Susan Rice, Obama National Security Advisor; Seth Rich',
    'SS': 'Secret Service',
    'ST': 'Seal Team (eg. Seal Team 6)',
    'STRAT': 'Strategic; Strategy Divisionsion within an AOC',
    'T2': 'Terminal 2',
    'TG': 'Trey Gowdy',
    'TM': 'Team',
    'TSA': 'Transportation Security Administration',
    'U1': 'Uranium 1',
    'UK': 'United Kingdom',
    'US': 'United States',
    'USSS': 'United States Secret Service',
    'VJ': 'Valerie Jarret, Former Senior Advisor to the President',
    'WH': 'White House',
    'WL': 'WikiLeaks',
    'WMD': 'Weapon of Mass Destruction',
    'WW': 'World War; World Wide',
    'X': 'MX, Mexico'
};